### ISSUE TITLE
KeyError: 'createdNote'

### ISSUE THREAD

**Issue by realkinetix** [aliceif/rsskey-special-aliceif-edition#1]
Hi there!

I know you may not be interested in this, but as you'd built a better machine, I thought I'd post this and see if it's a quick fix.

In both the original rsskey code and from the code here, when run it gets a key error when posting the first item. I almost wonder if this is an issue that showed up because python 3.12, or if I'm unlucky in some other fashion.  The error shows as follows:

`$ python src/rsskey.py 
  + Exception Group Traceback (most recent call last):
  |   File "/home/mkfeedbot1/rsskey-special-aliceif-edition/src/rsskey.py", line 126, in <module>
  |     if __name__ == '__main__': run(main)
  |                                ^^^^^^^^^
  |   File "/home/mkfeedbot1/rsskey-special-aliceif-edition/.venv/lib/python3.12/site-packages/trio/_core/_run.py", line 2417, in run
  |     raise runner.main_task_outcome.error
  |   File "/home/mkfeedbot1/rsskey-special-aliceif-edition/src/rsskey.py", line 116, in main
  |     async with AsyncExitStack() as stack, open_nursery() as nursery:
  |                                           ^^^^^^^^^^^^^^
  |   File "/home/mkfeedbot1/rsskey-special-aliceif-edition/.venv/lib/python3.12/site-packages/trio/_core/_run.py", line 1043, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/mkfeedbot1/rsskey-special-aliceif-edition/src/rsskey.py", line 78, in post
    |     parent = await note(text=rest, replyId=parent)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/mkfeedbot1/rsskey-special-aliceif-edition/src/rsskey.py", line 44, in create
    |     return response.json()['createdNote']['id']
    |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
    | KeyError: 'createdNote'
    +------------------------------------
`

If only I knew python better I suspect this might not be too hard to fix?

**Comment by aliceif** [comment]
Interesting, the thing I made this for is running on Python 3.12.3 (Ubuntu 24.04) and only has the occasional HTTP error in the systemd journal (I use a systemd timer to run this every hour or so). Haven't seen that key error yet.
What is your config like? (but please remove any passwords and api keys before posting)

**Comment by realkinetix** [comment]
Ah, you know what it is, it's the rate limiting that's getting in the way, so the returned data from the post looks like:

`{'error': {'message': 'Rate limit exceeded. Please try again later.', 'code': 'RATE_LIMIT_EXCEEDED', 'id': 'd5826d14-3982-4d2e-8011-b9e9f02499ef', 'kind': 'client', 'info': {'remaining': 0, 'reset': 1735490978, 'resetMs': 1735490978156, 'total': 1}}}`

I'm running Sharkey and they've asked me to test this with the next release as they've re-written the rate limiting code, so, maybe this will fix itself.

I look forward to better utilize your nice fix-ups to the rsskey code!
